# Generated by Django 3.2.13 on 2022-06-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('key', models.TextField(unique=True)),
                ('value', models.TextField()),
            ],
            options={
                'verbose_name': 'AccessPermission',
                'db_table': 'cirbox_access_permission',
            },
        ),
    ]
