# Generated by Django 3.2.13 on 2022-06-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateOrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('certificate_id', models.TextField()),
                ('product_type', models.TextField(choices=[('renta', 'RENTA'), ('vida_laboral', 'VIDA_LABORAL'), ('cirbe', 'CIRBE')])),
                ('status', models.TextField(choices=[('PENDIENTE', 'PENDIENTE'), ('COMPLETADO', 'COMPLETADO')], default='PENDIENTE')),
            ],
            options={
                'verbose_name': 'CertificateOrder',
                'db_table': 'cirbox_certificateorder',
                'unique_together': {('certificate_id', 'product_type')},
            },
        ),
    ]
