# Generated by Django 3.2.13 on 2022-06-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_certificateordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateordermodel',
            name='certificate_pass',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificateordermodel',
            name='person_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificateordermodel',
            name='person_type',
            field=models.TextField(choices=[('F', 'F'), ('J', 'J')], default='F'),
            preserve_default=False,
        ),
    ]
