# Generated by Django 3.2.13 on 2022-06-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20220620_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificateordermodel',
            old_name='certificate_pass',
            new_name='extra_info',
        ),
        migrations.RemoveField(
            model_name='certificateordermodel',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='certificateordermodel',
            name='person_type',
        ),
    ]
