# Generated by Django 3.2.13 on 2022-06-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20220621_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateordermodel',
            name='extra_info',
            field=models.TextField(null=True),
        ),
    ]
