# Generated by Django 3.2.13 on 2022-06-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_alter_certificateordermodel_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateordermodel',
            name='error',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='certificateordermodel',
            name='status',
            field=models.TextField(choices=[('COMPLETADO', 'COMPLETADO'), ('ERROR', 'ERROR'), ('PENDIENTE', 'PENDIENTE'), ('PROCESANDO', 'PROCESANDO')], default='PENDIENTE'),
        ),
    ]
