# Generated by Django 3.2.13 on 2022-06-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20220622_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateordermodel',
            name='extra_info',
            field=models.JSONField(null=True),
        ),
    ]
