# Generated by Django 3.2.13 on 2022-07-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_alter_certificateordermodel_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('context', models.TextField(null=True)),
                ('error', models.TextField(null=True)),
                ('response', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Log',
                'db_table': 'cirbox_log',
            },
        ),
    ]
