# Generated by Django 3.2.13 on 2022-07-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_alter_certificateordermodel_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateordermodel',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
