# Generated by Django 3.2.13 on 2022-07-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_alter_certificateordermodel_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateordermodel',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
