# Generated by Django 3.2.13 on 2022-07-14 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_certificateordermodel_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateOrderLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('context', models.TextField(null=True)),
                ('event', models.TextField(null=True)),
                ('extra_info', models.TextField(null=True)),
                ('certificate_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='src.certificateordermodel')),
            ],
            options={
                'verbose_name': 'CertificateOrderLog',
                'db_table': 'cirbox_certificateorder_log',
            },
        ),
    ]
