# Generated by Django 3.2.13 on 2022-11-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0018_auto_20220721_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateordermodel',
            name='brocode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='certificateordermodel',
            name='certificate_mode',
            field=models.TextField(choices=[('P12', 'P12'), ('PKCS11', 'PKCS11')], default='P12'),
        ),
    ]
