# Generated by Django 3.2.13 on 2022-11-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0019_auto_20221105_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateordermodel',
            name='brocode',
            field=models.TextField(null=True),
        ),
    ]
