# Generated by Django 3.2.13 on 2023-09-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0021_alter_certificateordermodel_certificate_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateordermodel',
            name='status',
            field=models.TextField(choices=[('COMPLETADO', 'COMPLETADO'), ('ERROR', 'ERROR'), ('PENDIENTE', 'PENDIENTE'), ('PROCESANDO', 'PROCESANDO'), ('NO_PROGRAMADO', 'NO_PROGRAMADO'), ('APPROVED', 'STATUS_APPROVED'), ('STARTED', 'STATUS_STARTED'), ('PROCESSING', 'STATUS_PROCESSING'), ('COMPLETED', 'STATUS_COMPLETED'), ('CANCELLED', 'STATUS_CANCELLED')], default='PENDIENTE'),
        ),
    ]
